---
# tasks file for ohmyzsh
- name: Make shure that git, curl and zsh is installed
  ansible.builtin.package:
    name:
      - zsh
      - curl
      - git
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Make shure that git, curl and zsh is installed
  ansible.builtin.apt:
    name:
      - zsh
      - curl
      - git
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Create directory
  ansible.builtin.file:
    path: ~/.oh-my-zsh
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
    state: directory
  become: true
  become_user: "{{ item }}"
  loop: "{{ ohmyzsh_user }}"

- name: Install ohmyzsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    version: master
  loop: "{{ ohmyzsh_user }}"

- name: Clone zsh plugin
  ansible.builtin.git:
    repo: "{{ item.1.1 }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item.1.0 }}"
    force: true
    version: master
  become: true
  become_user: "{{ item.0 }}"
  loop: "{{ ohmyzsh_user|product(ohmyzsh_plugins|zip(ohmyzsh_plugin_urls))|list }}"
  when: ohmyzsh_plugins | length > 0

- name: Create .zshrc file from template
  ansible.builtin.template:
    src: .zshrc.j2
    dest: ~/.zshrc
    mode: 0600
  become: true
  become_user: "{{ item }}"
  loop: "{{ ohmyzsh_user }}"

- name: Set zsh as default shell
  ansible.builtin.user: 
    name: "{{ item }}" 
    shell: /bin/zsh
  become: true
  loop: "{{ ohmyzsh_user }}"
