---
# tasks file for ohmyzsh
- name: Make shure that git, curl and zsh is installed.
  package:
    name:
      - zsh
      - curl
      - git
    state: present
    update_cache: yes
  become: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Make shure that git, curl and zsh is installed.
  apt:
    name:
      - zsh
      - curl
      - git
    state: present
    update_cache: yes
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Check if .oh-my-zsh exists in ~/.
  become: yes
  become_user: "{{ item }}"  
  stat: path=~/.oh-my-zsh
  register: diruser
  loop: "{{ user }}"

- name: Install oh-my-zsh.
  become: yes
  become_user: "{{ item.0 }}"
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: item.1 == False
  loop: "{{ user | zip(diruser.results|map(attribute='stat.exists'))|list }}"

- name: Clone zsh plugin.
  become: yes
  become_user: "{{ item.0 }}"
  git:
    repo: "{{ item.1.1 }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item.1.0 }}"
    force: yes
    version: master
  loop: "{{ user | product(plugin_names | zip(plugin_urls)) | list }}"
  when: custom_plugins | bool
  

- name: Create .zshrc file from template.
  ansible.builtin.template:
    src: .zshrc.j2
    dest: ~/.zshrc
  become: yes
  become_user: "{{ item }}"
  loop: "{{ user }}"

- name: Set zsh as default shell.
  user: 
    name: "{{ item }}" 
    shell: /bin/zsh
  become: yes
  loop: "{{ user }}"
